name: Continuous Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache deps.edn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: clj-${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@9.3
        with:
          cli: latest
          bb: latest

      - name: Lint
        run: clojure -Mclj-kondo --lint src

      - name: Test
        run: bin/kaocha

  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache deps.edn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: clj-${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@9.3
        with:
          cli: latest
          bb: latest

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Build
        run: bb build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'static-site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
